name: 'Trivy Scan'

on:
  pull_request:
    branches: [ "main" ]
  workflow_call:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  scan-filesystem:
    # Does not need to run in specific network segment yet, changes if we scan images from Harbor
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v.4.1.6
      - name: Run Trivy vulnerability scanner in fs mode and log results
        uses: aquasecurity/trivy-action@595be6a0f6560a0a8fc419ddf630567fc623531d # 0.22.0, uses 0.52.0 of Trivy
        with:
          scan-type: 'fs'
          format: 'table'
      - name: Run Trivy vulnerability scanner in fs mode and upload results to GH Advanced Security
        uses: aquasecurity/trivy-action@595be6a0f6560a0a8fc419ddf630567fc623531d # 0.22.0, uses 0.52.0 of Trivy
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy scan results to Github Security tab
        uses: github/codeql-action/upload-sarif@2e230e8fe0ad3a14a340ad0815ddb96d599d2aff # 3.25.8
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
